#!/bin/bash

DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/content"

val=
read_val() {
  read -p "$1" val
  val=${val::1}
  [[ ${val,,} == "y" ]]
  return $?
}

if read_val "Install dependencies? [y/N]"; then
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  sudo snap install universal-ctags
  mkdir -p ~/bin ~/.config/nvim
  sudo apt-get install neovim tig
fi

# Set up symlink.
# First arg is desired location.
# Second arg is file to link to.
function helper
{
  loc="$1"
  file="$DIR/$2"
  echo "Processing - $loc"

  if [[ -f "$loc" ]]; then
    diff="$(diff "$loc" "$file")"
    if [[ $diff ]] ; then
      echo "Diff between files: "
      echo "$diff"
      read -p "Replace contents? [y/N]: " var
      if [[ ${var,,} == 'y' ]]; then
        rm "$loc"
        ln -s "$file" "$loc"
      else
        echo "Skipping..."
      fi
    else
      rm "$loc"
      ln -s "$file" "$loc"
    fi
  else
    rm -f "$loc"
    ln -s "$file" "$loc"
  fi
}

helper ~/.bash_aliases bash_aliases
helper ~/bin/cctg cctg
helper ~/.gitconfig gitconfig
helper ~/.gitignore global-gitignore
helper ~/.config/nvim/init.vim init.vim
helper ~/.ssh/config config
