alias vi='nvim'
alias vim='nvim'
export EDITOR='nvim'

alias gis='git status'
alias gd='git diff'
alias gb='git rebase -i --autosquash origin/develop'
alias gf='git commit -a --fixup=HEAD'
alias gp='git push -u origin HEAD'

export ROS_WS_PATH=${HOME}/workspace
export MISO_CONFIG_PATH=${HOME}/.miso
export ML_MODEL_PATH=${ROS_WS_PATH}/src/ml_weights/classifiers/white_castle/white_castle_pilot.h5

alias w="cd ${ROS_WS_PATH}/src"

alias git-clean-branches='git remote prune origin && git branch --merged | grep -v \* | xargs git branch -D'

function sk() {
  eval $(ssh-agent)
  ssh-add
}

alias gk='git fetch --all && tig --all'
